"use client";

import { useState, useCallback } from "react";
import { prepareE2BFiles } from "@/lib/e2b-utils";
import type { ReactProject } from "@/app/types";

type ExportStatus = "idle" | "exporting" | "success" | "error";

interface UseGitHubExportProps {
  project: ReactProject | null;
  setError: (error: string) => void;
}

export function useGitHubExport({ project, setError }: UseGitHubExportProps) {
  const [showGitHubModal, setShowGitHubModal] = useState(false);
  const [githubToken, setGithubToken] = useState("");
  const [githubRepoName, setGithubRepoName] = useState("");
  const [githubPrivate, setGithubPrivate] = useState(false);
  const [githubExportStatus, setGithubExportStatus] = useState<ExportStatus>("idle");
  const [githubExportMessage, setGithubExportMessage] = useState("");
  const [githubRepoUrl, setGithubRepoUrl] = useState("");

  const exportToGitHub = useCallback(() => {
    if (!project) return;
    setGithubRepoName("my-nextjs-app");
    setGithubExportStatus("idle");
    setGithubExportMessage("");
    setGithubRepoUrl("");
    // Restore saved token if available
    const savedToken = localStorage.getItem("github_token");
    if (savedToken) setGithubToken(savedToken);
    setShowGitHubModal(true);
  }, [project]);

  const pushToGitHub = useCallback(async () => {
    if (!project || !githubToken || !githubRepoName) return;

    setGithubExportStatus("exporting");
    setGithubExportMessage("Creating repository...");

    const headers = {
      Authorization: `token ${githubToken}`,
      Accept: "application/vnd.github.v3+json",
      "Content-Type": "application/json",
    };

    try {
      // Save token for future use
      localStorage.setItem("github_token", githubToken);

      // 1. Create the repository
      const createRepoRes = await fetch("https://api.github.com/user/repos", {
        method: "POST",
        headers,
        body: JSON.stringify({
          name: githubRepoName,
          description: "Next.js app generated by Pocket Dev",
          private: githubPrivate,
          auto_init: false,
        }),
      });

      if (!createRepoRes.ok) {
        const errData = await createRepoRes.json();
        if (
          createRepoRes.status === 422 &&
          errData.errors?.some((e: any) =>
            e.message?.includes("already exists"),
          )
        ) {
          throw new Error(
            `Repository "${githubRepoName}" already exists. Choose a different name.`,
          );
        }
        if (createRepoRes.status === 401) {
          throw new Error(
            "Invalid GitHub token. Please check your personal access token.",
          );
        }
        throw new Error(
          errData.message ||
            `Failed to create repository (${createRepoRes.status})`,
        );
      }

      const repo = await createRepoRes.json();
      const owner = repo.owner.login;
      const repoName = repo.name;

      setGithubExportMessage("Preparing files...");

      // Build all project files
      const allFiles = prepareE2BFiles(project);

      allFiles[".gitignore"] =
        `node_modules\n.next\nout\nbuild\n.DS_Store\n*.pem\nnpm-debug.log*\n.env*.local\n.vercel\n*.tsbuildinfo\nnext-env.d.ts\n`;

      allFiles["README.md"] =
        `# ${githubRepoName}\n\nNext.js app generated by [Pocket Dev](https://pocketdev.app).\n\n## Getting Started\n\n\`\`\`bash\nnpm install\nnpm run dev\n\`\`\`\n\nOpen [http://localhost:3000](http://localhost:3000).\n\n## Deploy\n\nDeploy with [Vercel](https://vercel.com/new).\n`;

      // 2. Create blobs for each file
      setGithubExportMessage("Uploading files...");
      const blobs: Array<{ path: string; sha: string }> = [];

      for (const [path, content] of Object.entries(allFiles)) {
        const blobRes = await fetch(
          `https://api.github.com/repos/${owner}/${repoName}/git/blobs`,
          {
            method: "POST",
            headers,
            body: JSON.stringify({
              content: btoa(unescape(encodeURIComponent(content))),
              encoding: "base64",
            }),
          },
        );

        if (!blobRes.ok) throw new Error(`Failed to create blob for ${path}`);
        const blob = await blobRes.json();
        blobs.push({ path, sha: blob.sha });
      }

      // 3. Create tree
      setGithubExportMessage("Creating commit...");
      const treeRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/trees`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({
            tree: blobs.map((b) => ({
              path: b.path,
              mode: "100644",
              type: "blob",
              sha: b.sha,
            })),
          }),
        },
      );

      if (!treeRes.ok) throw new Error("Failed to create tree");
      const tree = await treeRes.json();

      // 4. Create commit
      const commitRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/commits`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({
            message: "Initial commit from Pocket Dev",
            tree: tree.sha,
          }),
        },
      );

      if (!commitRes.ok) throw new Error("Failed to create commit");
      const commit = await commitRes.json();

      // 5. Create main branch ref
      const refRes = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/git/refs`,
        {
          method: "POST",
          headers,
          body: JSON.stringify({
            ref: "refs/heads/main",
            sha: commit.sha,
          }),
        },
      );

      if (!refRes.ok) throw new Error("Failed to create branch ref");

      setGithubRepoUrl(repo.html_url);
      setGithubExportStatus("success");
      setGithubExportMessage("Successfully pushed to GitHub!");
    } catch (error: any) {
      console.error("GitHub export error:", error);
      setGithubExportStatus("error");
      setGithubExportMessage(error.message || "Failed to export to GitHub");
    }
  }, [project, githubToken, githubRepoName, githubPrivate]);

  return {
    // State
    showGitHubModal,
    githubToken,
    githubRepoName,
    githubPrivate,
    githubExportStatus,
    githubExportMessage,
    githubRepoUrl,
    // Setters
    setShowGitHubModal,
    setGithubToken,
    setGithubRepoName,
    setGithubPrivate,
    setGithubExportStatus,
    setGithubExportMessage,
    setGithubRepoUrl,
    // Functions
    exportToGitHub,
    pushToGitHub,
  };
}
