interface GeneratedFile {
  path: string;
  content: string;
}

export interface ReactProject {
  files: GeneratedFile[];
  dependencies: Record<string, string>;
}

export interface E2BFiles {
  [path: string]: string;
}

/**
 * Detects if a project includes Firebase authentication
 */
export function hasAuthentication(project: ReactProject): boolean {
  return project.files.some(f =>
    f.content.includes('firebase/auth') ||
    f.content.includes('firebase/firestore') ||
    f.content.includes('AuthProvider')
  );
}

/**
 * Prepares files for E2B with Next.js App Router structure
 * Includes all necessary config files for Next.js
 */
export function prepareE2BFiles(project: ReactProject): E2BFiles {
  const files: E2BFiles = {};

  // Config files that will be generated below — skip AI-generated duplicates
  const managedConfigFiles = new Set([
    "package.json",
    "tsconfig.json",
    "next.config.js",
    "next.config.ts",
    "tailwind.config.js",
    "tailwind.config.ts",
    "postcss.config.js",
    "postcss.config.mjs",
  ]);

  // Add all generated files from AI, excluding config files we manage ourselves
  // But first, extract any extra dependencies from AI-generated package.json
  let aiDeps: Record<string, string> = {};
  const aiPkgFile = project.files.find((f) => f.path === "package.json");
  if (aiPkgFile) {
    try {
      const aiPkg = JSON.parse(aiPkgFile.content);
      aiDeps = aiPkg.dependencies || {};
    } catch { /* ignore parse errors */ }
  }

  project.files.forEach((f) => {
    if (managedConfigFiles.has(f.path)) return;
    files[f.path] = f.content;
  });

  // Add package.json with Next.js scripts — merge AI deps + project deps
  files["package.json"] = JSON.stringify({
    name: "generated-nextjs-app",
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint"
    },
    dependencies: {
      ...aiDeps,
      ...project.dependencies,
      "next": "^14.0.0",
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "lucide-react": "^0.294.0",
      ...(hasAuthentication(project) ? { "firebase": "^10.7.1" } : {}),
    },
    devDependencies: {
      "@types/node": "^20",
      "@types/react": "^18",
      "@types/react-dom": "^18",
      "typescript": "^5",
      "tailwindcss": "^3.3.0",
      "autoprefixer": "^10.4.16",
      "postcss": "^8.4.31"
    }
  }, null, 2);

  // Add next.config.js
  files["next.config.js"] = `/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'replicate.delivery',
      },
      {
        protocol: 'https',
        hostname: 'firebasestorage.googleapis.com',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: 'picsum.photos',
      },
    ],
  },
};
module.exports = nextConfig;`;

  // Add tailwind.config.js with common custom color fallbacks
  // (Gemini sometimes generates bg-primary/bg-secondary — these prevent build errors)
  files["tailwind.config.js"] = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: { DEFAULT: '#2563eb', 50: '#eff6ff', 100: '#dbeafe', 200: '#bfdbfe', 300: '#93c5fd', 400: '#60a5fa', 500: '#3b82f6', 600: '#2563eb', 700: '#1d4ed8', 800: '#1e40af', 900: '#1e3a8a' },
        secondary: { DEFAULT: '#7c3aed', 50: '#f5f3ff', 100: '#ede9fe', 200: '#ddd6fe', 300: '#c4b5fd', 400: '#a78bfa', 500: '#8b5cf6', 600: '#7c3aed', 700: '#6d28d9', 800: '#5b21b6', 900: '#4c1d95' },
        accent: { DEFAULT: '#f59e0b', 50: '#fffbeb', 100: '#fef3c7', 200: '#fde68a', 300: '#fcd34d', 400: '#fbbf24', 500: '#f59e0b', 600: '#d97706', 700: '#b45309', 800: '#92400e', 900: '#78350f' },
      },
    },
  },
  plugins: [],
}`;

  // Add postcss.config.js
  files["postcss.config.js"] = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`;

  // Add tsconfig.json
  files["tsconfig.json"] = JSON.stringify({
    compilerOptions: {
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: {
        "@/*": ["./*"]
      }
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"]
  }, null, 2);

  // Add globals.css (if not already generated by AI)
  if (!files["app/globals.css"]) {
    files["app/globals.css"] = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}`;
  }

  // Add global error handler to catch ChunkLoadError and auto-reload
  if (!files["app/global-error.tsx"]) {
    files["app/global-error.tsx"] = `"use client";
import { useEffect } from "react";
export default function GlobalError({ error, reset }: { error: Error & { digest?: string }; reset: () => void }) {
  useEffect(() => {
    if (error.name === "ChunkLoadError" || error.message?.includes("Loading chunk")) {
      window.location.reload();
    }
  }, [error]);
  return (
    <html><body style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh", fontFamily: "system-ui", background: "#0a0a0a", color: "#fff" }}>
      <div style={{ textAlign: "center" }}>
        <h2 style={{ marginBottom: 16 }}>Something went wrong</h2>
        <button onClick={() => reset()} style={{ padding: "8px 20px", background: "#3b82f6", color: "#fff", border: "none", borderRadius: 8, cursor: "pointer" }}>Try again</button>
      </div>
    </body></html>
  );
}`;
  }

  // Check if auth is present and add setup guide
  const hasFirebaseAuth = project.files.some(f =>
    f.content.includes('firebase/auth') ||
    f.content.includes('firebase/firestore') ||
    f.content.includes('AuthProvider')
  );

  if (hasFirebaseAuth) {
    files["README.md"] = `# 🎉 Your Generated Next.js App

This app was generated by **Pocket Dev** and includes production-ready features!

## ✨ Features

- ⚡ **Next.js 14** with App Router
- 🎨 **Tailwind CSS** for styling
- 🔐 **Firebase Authentication** (Pre-configured!)
- 🔒 **Multi-Tenancy** (Isolated user authentication per app)
- 🗄️ **Firestore Database** (Real-time data sync)
- 📦 **Firebase Storage** (File uploads ready)

## 🔐 Authentication - Zero Setup Required!

Your app comes with **fully configured Firebase authentication** - no manual setup needed!

### What's Included:

✅ **Email/Password Authentication**
✅ **Google Sign-In** (OAuth ready)
✅ **User Profiles** (/profile page)
✅ **Protected Routes** (automatic auth checks)
✅ **Firestore Database** (user data scoped per user)

### How It Works:

1. **Sign Up**: Visit \`/sign-up\` to create an account
2. **Sign In**: Visit \`/sign-in\` to log in
3. **Profile**: View your profile at \`/profile\`
4. **Sign Out**: Click the "Sign Out" button in the navbar

### Data Storage:

All user data is automatically stored in Firestore under:
\`\`\`
users/{userId}/
  ├── cart/
  ├── preferences/
  ├── orders/
  └── [other collections]/
\`\`\`

Data is **automatically synced** across devices and sessions!

## 🚀 Getting Started

1. Click the **"Sign Up"** link in the navbar
2. Create an account with email or Google
3. Start using your app immediately!

## 📝 Adding More Features

### Example: Add a Shopping Cart

\`\`\`typescript
import { useAuth } from '@/app/components/AuthProvider';
import { db } from '@/lib/firebase-config';
import { doc, setDoc, onSnapshot } from 'firebase/firestore';

function useCart() {
  const { user } = useAuth();
  const [cart, setCart] = useState([]);

  useEffect(() => {
    if (!user) return;

    const unsubscribe = onSnapshot(
      doc(db, 'users', user.uid, 'cart', 'items'),
      (doc) => setCart(doc.data()?.items || [])
    );

    return () => unsubscribe();
  }, [user]);

  return cart;
}
\`\`\`

## 🎨 Customization

- **Styling**: Edit Tailwind classes in components
- **Auth Pages**: Customize \`app/sign-in/page.tsx\` and \`app/sign-up/page.tsx\`
- **Profile**: Edit \`app/profile/page.tsx\`
- **Navbar**: Modify \`app/components/Navbar.tsx\`

## 📚 Documentation

- [Firebase Auth Docs](https://firebase.google.com/docs/auth)
- [Firestore Docs](https://firebase.google.com/docs/firestore)
- [Next.js Docs](https://nextjs.org/docs)
- [Tailwind CSS Docs](https://tailwindcss.com/docs)

---

**Generated with ❤️ by [Pocket Dev](https://pocket-dev.com)**
`;
  }

  return files;
}

/**
 * Computes the difference between old and new files
 * Returns arrays of files to write and files to delete
 */
export function computeFileDiff(
  oldFiles: Record<string, string>,
  newFiles: Record<string, string>
): {
  toWrite: Array<{ path: string; data: string }>;
  toDelete: string[];
} {
  const toWrite: Array<{ path: string; data: string }> = [];
  const toDelete: string[] = [];

  // Find files that are new or changed
  for (const [path, content] of Object.entries(newFiles)) {
    if (oldFiles[path] !== content) {
      toWrite.push({ path, data: content });
    }
  }

  // Find files that were deleted
  for (const path of Object.keys(oldFiles)) {
    if (!(path in newFiles)) {
      toDelete.push(path);
    }
  }

  return { toWrite, toDelete };
}
