import type { VM } from '@stackblitz/sdk';

interface GeneratedFile {
  path: string;
  content: string;
}

export interface ReactProject {
  files: GeneratedFile[];
  dependencies: Record<string, string>;
}

export interface StackBlitzFiles {
  [path: string]: string;
}

/**
 * Detects if a project includes Firebase authentication
 */
export function hasAuthentication(project: ReactProject): boolean {
  return project.files.some(f =>
    f.content.includes('firebase/auth') ||
    f.content.includes('firebase/firestore') ||
    f.content.includes('AuthProvider')
  );
}

/**
 * Prepares files for StackBlitz with Next.js App Router structure
 * Includes all necessary config files for Next.js
 */
export function prepareStackBlitzFiles(project: ReactProject): StackBlitzFiles {
  const files: StackBlitzFiles = {};

  // Add all generated files from AI
  project.files.forEach((f) => {
    files[f.path] = f.content;
  });

  // Add package.json with Next.js scripts
  files["package.json"] = JSON.stringify({
    name: "generated-nextjs-app",
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint"
    },
    dependencies: {
      ...project.dependencies,
      "next": "^14.0.0",
      "react": "^18.2.0",
      "react-dom": "^18.2.0",
      "lucide-react": "^0.294.0",
      ...(hasAuthentication(project) ? { "firebase": "^10.7.1" } : {}),
    },
    devDependencies: {
      "@types/node": "^20",
      "@types/react": "^18",
      "@types/react-dom": "^18",
      "typescript": "^5",
      "tailwindcss": "^3.3.0",
      "autoprefixer": "^10.4.16",
      "postcss": "^8.4.31"
    }
  }, null, 2);

  // Add next.config.js
  files["next.config.js"] = `/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
      {
        protocol: 'https',
        hostname: 'via.placeholder.com',
      },
      {
        protocol: 'https',
        hostname: 'firebasestorage.googleapis.com',
      },
      {
        protocol: 'https',
        hostname: 'picsum.photos',
      },
    ],
  },
};
module.exports = nextConfig;`;

  // Add tailwind.config.js
  files["tailwind.config.js"] = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}`;

  // Add postcss.config.js
  files["postcss.config.js"] = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`;

  // Add tsconfig.json
  files["tsconfig.json"] = JSON.stringify({
    compilerOptions: {
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: {
        "@/*": ["./*"]
      }
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"]
  }, null, 2);

  // Add globals.css (if not already generated by AI)
  if (!files["app/globals.css"]) {
    files["app/globals.css"] = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}`;
  }

  // Add global error handler to catch ChunkLoadError and auto-reload
  if (!files["app/global-error.tsx"]) {
    files["app/global-error.tsx"] = `"use client";
import { useEffect } from "react";
export default function GlobalError({ error, reset }: { error: Error & { digest?: string }; reset: () => void }) {
  useEffect(() => {
    if (error.name === "ChunkLoadError" || error.message?.includes("Loading chunk")) {
      window.location.reload();
    }
  }, [error]);
  return (
    <html><body style={{ display: "flex", alignItems: "center", justifyContent: "center", minHeight: "100vh", fontFamily: "system-ui", background: "#0a0a0a", color: "#fff" }}>
      <div style={{ textAlign: "center" }}>
        <h2 style={{ marginBottom: 16 }}>Something went wrong</h2>
        <button onClick={() => reset()} style={{ padding: "8px 20px", background: "#3b82f6", color: "#fff", border: "none", borderRadius: 8, cursor: "pointer" }}>Try again</button>
      </div>
    </body></html>
  );
}`;
  }

  // Check if auth is present and add setup guide
  const hasFirebaseAuth = project.files.some(f =>
    f.content.includes('firebase/auth') ||
    f.content.includes('firebase/firestore') ||
    f.content.includes('AuthProvider')
  );

  if (hasFirebaseAuth) {
    files["README.md"] = `# 🎉 Your Generated Next.js App

This app was generated by **Pocket Dev** and includes production-ready features!

## ✨ Features

- ⚡ **Next.js 14** with App Router
- 🎨 **Tailwind CSS** for styling
- 🔐 **Firebase Authentication** (Pre-configured!)
- 🔒 **Multi-Tenancy** (Isolated user authentication per app)
- 🗄️ **Firestore Database** (Real-time data sync)
- 📦 **Firebase Storage** (File uploads ready)

## 🔐 Authentication - Zero Setup Required!

Your app comes with **fully configured Firebase authentication** - no manual setup needed!

### What's Included:

✅ **Email/Password Authentication**
✅ **Google Sign-In** (OAuth ready)
✅ **User Profiles** (/profile page)
✅ **Protected Routes** (automatic auth checks)
✅ **Firestore Database** (user data scoped per user)

### How It Works:

1. **Sign Up**: Visit \`/sign-up\` to create an account
2. **Sign In**: Visit \`/sign-in\` to log in
3. **Profile**: View your profile at \`/profile\`
4. **Sign Out**: Click the "Sign Out" button in the navbar

### Data Storage:

All user data is automatically stored in Firestore under:
\`\`\`
users/{userId}/
  ├── cart/
  ├── preferences/
  ├── orders/
  └── [other collections]/
\`\`\`

Data is **automatically synced** across devices and sessions!

## 🚀 Getting Started

1. Click the **"Sign Up"** link in the navbar
2. Create an account with email or Google
3. Start using your app immediately!

## 📝 Adding More Features

### Example: Add a Shopping Cart

\`\`\`typescript
import { useAuth } from '@/app/components/AuthProvider';
import { db } from '@/lib/firebase-config';
import { doc, setDoc, onSnapshot } from 'firebase/firestore';

function useCart() {
  const { user } = useAuth();
  const [cart, setCart] = useState([]);

  useEffect(() => {
    if (!user) return;

    const unsubscribe = onSnapshot(
      doc(db, 'users', user.uid, 'cart', 'items'),
      (doc) => setCart(doc.data()?.items || [])
    );

    return () => unsubscribe();
  }, [user]);

  return cart;
}
\`\`\`

## 🎨 Customization

- **Styling**: Edit Tailwind classes in components
- **Auth Pages**: Customize \`app/sign-in/page.tsx\` and \`app/sign-up/page.tsx\`
- **Profile**: Edit \`app/profile/page.tsx\`
- **Navbar**: Modify \`app/components/Navbar.tsx\`

## 📚 Documentation

- [Firebase Auth Docs](https://firebase.google.com/docs/auth)
- [Firestore Docs](https://firebase.google.com/docs/firestore)
- [Next.js Docs](https://nextjs.org/docs)
- [Tailwind CSS Docs](https://tailwindcss.com/docs)

---

**Generated with ❤️ by [Pocket Dev](https://pocket-dev.com)**
`;
  }

  return files;
}

/**
 * Waits for the StackBlitz preview to be ready
 * Polls for preview URL availability
 * Note: This is optional - the embed will work even if this times out
 */
export async function waitForPreview(vm: VM, timeout: number = 10000): Promise<void> {
  const startTime = Date.now();
  const pollInterval = 500;

  return new Promise((resolve, reject) => {
    const checkPreview = async () => {
      try {
        const url = await vm.preview.getUrl();
        if (url) {
          resolve();
          return;
        }
      } catch (e) {
        // Preview not ready yet - this is normal during startup
      }

      if (Date.now() - startTime > timeout) {
        // Don't treat this as a critical error - just log it
        console.log('Preview URL detection timed out, but embed is running');
        resolve(); // Resolve instead of reject
        return;
      }

      setTimeout(checkPreview, pollInterval);
    };

    checkPreview();
  });
}
